name: feature
description: A Commons Module containing all Flutter abstractions and utils

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system
  domain:
    path: ../domain
  commons:
    path: ../commons
  model:
    path: ../model
  intl: 0.17.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.1.11
  injectable_generator: 1.5.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: br.com.askscience.commons
    iosBundleIdentifier: br.com.askscience.commons