name: model
description: A Model Module containing all Models

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.1.11
  injectable_generator: 1.5.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: br.com.askscience.model
    iosBundleIdentifier: br.com.askscience.model