name: ask_science
description: Comunidade de dúvidas e relatos médicos
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  commons:
    path: commons
  model:
    path: model
  data:
    path: data
  domain:
    path: domain
  feature:
    path: feature
  design_system:
    path: design_system
  injectable: ^1.5.3
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  flushbar: ^1.10.4
  firebase_remote_config: ^3.0.6
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.11
  injectable_generator: 1.5.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true



