name: commons
description: A Commons Module containing all Flutter abstractions and utils

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.1.11

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: br.com.askscience.commons
    iosBundleIdentifier: br.com.askscience.commons