name: commons
description: A Commons Module containing all Flutter abstractions and utils

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: 1.5.3
  get_it: 7.2.0
  dio: 4.0.6
  intl: 0.17.0
  firebase_remote_config: ^3.0.6
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.1.11
  injectable_generator: 1.5.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: br.com.askscience.commons
    iosBundleIdentifier: br.com.askscience.commons